#!/usr/bin/env bash
#
# A wizard: walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear: wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title": opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later. Nothing is stored anywhere until the last stage.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name": clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "...": a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "...": a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL: open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser, visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, visit it manually: $url"
}

# pause "msg": wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question": y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt": read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt": like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE: upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE: set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name, gh not ready; set it later"
}

# set_var NAME VALUE: set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish: clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Nothing captured here is written to a file. The certificate and its password
# are the keys to signing software as this company, and a .env holding them
# would outlive the reason it existed. They go from your clipboard to GitHub's
# secret store and nowhere else.
ENV_FILE="/dev/null"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SELF_SERVE="no"

banner "SecureSend for macOS: signing and notarization"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools, and which repository these secrets will land on."
printf '\n'

cd "$REPO_DIR"

MISSING=""
for tool in gh security xcrun openssl; do
  command -v "$tool" > /dev/null 2>&1 || MISSING="$MISSING $tool"
done
if [[ -n "$MISSING" ]]; then
  warn "missing:$MISSING"
  say "Install those first. gh comes from Homebrew; the rest ship with macOS and"
  say "the Xcode Command Line Tools (xcode-select --install)."
  exit 1
fi
note "tools: gh, security, xcrun, openssl all present"

if ! gh auth status > /dev/null 2>&1; then
  warn "gh is not logged in. Run: gh auth login"
  exit 1
fi
note "gh: logged in"

REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner 2> /dev/null || echo "")"
if [[ -z "$REPO" ]]; then
  warn "this directory is not a GitHub repository gh can see: $REPO_DIR"
  exit 1
fi
printf '\n'
say "Secrets will be set on ${BOLD}${REPO}${RESET}."
if ! confirm "Is that the right repository?"; then
  say "Run this from a checkout of the repository you meant."
  exit 1
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Who is allowed to create these"
say "Two artifacts are needed, and Apple gates both on the account, not on you:"
printf '\n'
step "A Developer ID Application certificate. Only the ${BOLD}Account Holder${RESET} of"
say "  the Apple Developer team can create one, and a team may hold five in total."
step "An App Store Connect API key for notarization. Needs ${BOLD}Account Holder or Admin${RESET}."
printf '\n'
say "For SecureSend that team is Morgan Jonasson Consulting AB, and the Account"
say "Holder is Morgan. So either you are signed in to that account, or Morgan"
say "makes both and sends them to you. This wizard handles both."
printf '\n'

if confirm "Are you signed in to that Apple Developer account yourself?"; then
  SELF_SERVE="yes"
  note "you will create both artifacts in the next stages"
else
  SELF_SERVE="no"
  printf '\n'
  say "Here is the message to send Morgan. It asks for both artifacts at once so"
  say "he only has to sit down for this a single time."
  printf '\n'
  REQUEST=$(
    cat << 'REQUEST_END'
Hi Morgan, I need two things from the MJC AB Apple Developer account to sign and
notarize the SecureSend Mac app. Both are Account Holder gated, which is why I
cannot make them myself. It is about fifteen minutes in total.

1. A Developer ID Application certificate.
   - In Keychain Access: Certificate Assistant > Request a Certificate From a
     Certificate Authority. Enter your email, leave CA Email blank, choose
     "Saved to disk". That produces a .certSigningRequest file.
   - At https://developer.apple.com/account/resources/certificates/add pick
     Software > Developer ID > Developer ID Application, upload that file,
     continue, and download the .cer.
   - Double-click the .cer to install it, then in Keychain Access find it under
     login > My Certificates, right-click > Export, and save it as a .p12 with
     a password. The .p12 and that password are what I need.
   - The team can hold five of these in total, so this does not use anything up
     that we cannot replace.

2. An App Store Connect API key for notarization.
   - At https://appstoreconnect.apple.com/access/integrations/api go to
     Users and Access > Integrations > App Store Connect API > Team Keys, then
     Generate API Key. Name it something like "SecureSend notarization" and
     give it the Developer role.
   - Send me the downloaded .p8 file, plus the Key ID and the Issuer ID shown
     on that page. Apple only lets the .p8 be downloaded once.

Please send the .p12 password as a SecureSend link rather than in the same
message as the file: https://securesend.dev. The link opens once and then it is
gone. The files themselves can come any way that suits you.

Thank you. This is a one-time favour; we move to our own membership when the
product pays for it.
REQUEST_END
  )
  printf '%s\n' "$REQUEST"
  printf '\n'
  if command -v pbcopy > /dev/null 2>&1; then
    if confirm "Copy that message to the clipboard?"; then
      printf '%s' "$REQUEST" | pbcopy
      note "copied"
    fi
  fi
  printf '\n'
  say "Stop here until the files arrive. Re-run this wizard when they have."
  if ! confirm "Do you have the .p12 and the .p8 in hand right now?"; then
    say "Nothing has been changed. See you when they land."
    exit 0
  fi
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "The Developer ID certificate"
if [[ "$SELF_SERVE" == "yes" ]]; then
  say "First a certificate signing request, which is how Apple learns your key."
  step "Open Keychain Access > Certificate Assistant > Request a Certificate"
  say "  From a Certificate Authority. Enter your email, leave CA Email blank,"
  say "  choose 'Saved to disk', and save the .certSigningRequest file."
  pause "Done? Press Enter."
  printf '\n'
  open_url "https://developer.apple.com/account/resources/certificates/add"
  step "Under Software choose Developer ID, then Developer ID Application, Continue."
  step "Upload the .certSigningRequest, Continue, then Download the .cer."
  step "Double-click the .cer to install it into your keychain."
  pause "Done? Press Enter."
  printf '\n'
  step "In Keychain Access, under login > My Certificates, find the row starting"
  say "  'Developer ID Application:'. Right-click it, Export, save as a .p12,"
  say "  and give it a password you can paste in a moment."
  pause "Done? Press Enter."
  printf '\n'
fi

say "Now point this wizard at that .p12 file."
note "drag the file into this terminal to paste its path"
ask P12_PATH "Path to the .p12:"
# Dragging a file into Terminal pastes its path with spaces backslash-escaped,
# and some shells wrap it in quotes. Undo both before looking for the file.
P12_PATH="${P12_PATH/#\~/$HOME}"
P12_PATH="${P12_PATH%\'}"
P12_PATH="${P12_PATH#\'}"
P12_PATH="${P12_PATH//\\ / }"
if [[ ! -f "$P12_PATH" ]]; then
  warn "no file at: $P12_PATH"
  exit 1
fi
ask_secret P12_PASSWORD "Password for the .p12:"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Checking the certificate is the right one"
say "Importing it into a throwaway keychain, which is exactly what the release"
say "workflow does on the runner. If an identity comes back here, one comes back"
say "there."
printf '\n'

CHECK_DIR="$(mktemp -d)"
CHECK_KEYCHAIN="$CHECK_DIR/check.keychain-db"
CHECK_PASSWORD="$(openssl rand -base64 24)"

cleanup_check() {
  security delete-keychain "$CHECK_KEYCHAIN" > /dev/null 2>&1 || true
  rm -rf "$CHECK_DIR"
}
trap cleanup_check EXIT

security create-keychain -p "$CHECK_PASSWORD" "$CHECK_KEYCHAIN" > /dev/null
security unlock-keychain -p "$CHECK_PASSWORD" "$CHECK_KEYCHAIN" > /dev/null

if ! security import "$P12_PATH" -k "$CHECK_KEYCHAIN" -P "$P12_PASSWORD" -T /usr/bin/codesign > /dev/null 2>&1; then
  warn "macOS refused to import that file. Usually the password is wrong, or the"
  warn "export was 'Certificate' rather than the certificate with its private key."
  exit 1
fi

IDENTITY="$(security find-identity -v -p codesigning "$CHECK_KEYCHAIN" | { grep "Developer ID Application" || true; } | sed -n 's/.*"\(.*\)".*/\1/p')"
if [[ -z "$IDENTITY" ]]; then
  warn "that .p12 imported, but it holds no Developer ID Application identity."
  say "What it does hold:"
  security find-identity -v -p codesigning "$CHECK_KEYCHAIN" || true
  printf '\n'
  say "An Apple Development or Apple Distribution certificate cannot sign a"
  say "public download. It has to be Developer ID Application."
  exit 1
fi
if [[ "$(printf '%s\n' "$IDENTITY" | grep -c .)" != "1" ]]; then
  warn "that .p12 holds more than one Developer ID Application identity:"
  printf '%s\n' "$IDENTITY"
  say "The workflow expects exactly one. Export a single certificate."
  exit 1
fi

printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$IDENTITY"
cleanup_check
trap - EXIT
printf '\n'
note "the workflow reads this name out of the certificate, so it is not a secret"
note "you have to keep in step by hand"
pause "Press Enter to continue."

MACOS_CERTIFICATE="$(base64 < "$P12_PATH" | tr -d '\n')"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The notarization key"
if [[ "$SELF_SERVE" == "yes" ]]; then
  say "An App Store Connect API key is what lets CI hand builds to Apple without"
  say "anybody's Apple ID password living in a repository."
  printf '\n'
  open_url "https://appstoreconnect.apple.com/access/integrations/api"
  step "Users and Access > Integrations > App Store Connect API, Team Keys tab."
  step "Generate API Key. Name it 'SecureSend notarization', role Developer."
  step "Download the .p8. Apple allows that download exactly once."
  step "Note the Key ID on the row, and the Issuer ID shown above the list."
  pause "Done? Press Enter."
  printf '\n'
fi

note "drag the file into this terminal to paste its path"
ask P8_PATH "Path to the .p8:"
P8_PATH="${P8_PATH/#\~/$HOME}"
P8_PATH="${P8_PATH%\'}"
P8_PATH="${P8_PATH#\'}"
P8_PATH="${P8_PATH//\\ / }"
if [[ ! -f "$P8_PATH" ]]; then
  warn "no file at: $P8_PATH"
  exit 1
fi
ask NOTARY_KEY_ID "Key ID:"
ask NOTARY_ISSUER_ID "Issuer ID:"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Checking the key can actually talk to Apple"
say "Asking Apple for this team's notarization history. It returns nothing on a"
say "team that has never notarized anything, which is fine. What matters is that"
say "Apple answers at all, because that means the three values agree."
printf '\n'

if xcrun notarytool history \
  --key "$P8_PATH" \
  --key-id "$NOTARY_KEY_ID" \
  --issuer "$NOTARY_ISSUER_ID" > /dev/null 2>&1; then
  printf '  %s✓%s Apple accepted the key\n' "$GREEN" "$RESET"
else
  warn "Apple refused those credentials. Its own words:"
  printf '\n'
  xcrun notarytool history --key "$P8_PATH" --key-id "$NOTARY_KEY_ID" --issuer "$NOTARY_ISSUER_ID" 2>&1 | sed 's/^/    /' || true
  printf '\n'
  say "Usually one of: the Key ID and Issuer ID belong to different keys, the .p8"
  say "is not the one that matches this Key ID, or the key's role is too narrow."
  say "If you suspect the role, generate a fresh key with the App Manager role."
  exit 1
fi

NOTARY_KEY="$(base64 < "$P8_PATH" | tr -d '\n')"
printf '\n'
pause "Press Enter to install these on $REPO."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Installing the five secrets"
say "Everything above has been verified, so these go to $REPO now."
printf '\n'

set_secret MACOS_CERTIFICATE "$MACOS_CERTIFICATE"
set_secret MACOS_CERTIFICATE_PASSWORD "$P12_PASSWORD"
set_secret NOTARY_KEY "$NOTARY_KEY"
set_secret NOTARY_KEY_ID "$NOTARY_KEY_ID"
set_secret NOTARY_ISSUER_ID "$NOTARY_ISSUER_ID"

printf '\n'
say "That is the whole setup. A release is now two commands:"
printf '\n'
say "  ./scripts/version.sh 0.1.0"
say "  git push --follow-tags"
printf '\n'
say "The tag starts the workflow, and a notarized dmg appears on the release."
printf '\n'
warn "Keep the .p12 and the .p8 somewhere safe, or in the bin. GitHub will not"
warn "show them again, and Apple will not re-issue the .p8 at all."
printf '\n'

if confirm "Delete the .p12 and .p8 from disk now?"; then
  rm -f "$P12_PATH" "$P8_PATH"
  note "deleted. They live in GitHub's secret store now."
fi

finish
